### ISSUE TITLE
Error Numpy

### ISSUE THREAD

**Issue by Volko61** [MikeBirdTech/open-interpreter-termux#14]
Collecting chroma-hnswlib==0.7.3 (from chromadb<0.5.0,>=0.4.22->aifs<0.0.10,>=0.0.9->open-interpreter)
  Downloading chroma-hnswlib-0.7.3.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
          from . import multiarray
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
          from . import overrides
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311.so"...

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
          from numpy.__config__ import show as show_config
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
          from numpy.core._multiarray_umath import (
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
          raise ImportError(msg)
      ImportError:

      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was
      installed.

      We have compiled some common reasons and troubleshooting tips at:

          https://numpy.org/devdocs/user/troubleshooting-importerror.html

      Please note and check the following:

        * The Python version is: Python3.11 from "/data/data/com.termux/files/usr/bin/python3.11"
        * The NumPy version is: "1.26.4"

      and make sure that they are the versions you expect.
      Please carefully study the documentation linked above for further help.

      Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311.so"...

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-9w7vud48/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
          raise ImportError(msg) from e
      ImportError: Error importing numpy: you should not try to import numpy from
              its source directory; please exit the numpy source tree, and relaunch
              your python interpreter from there.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
~ $

**Comment by Badashphilosophy** [comment]
Hey buddy, had the same problem. Solved it by installing an earlier version of open interpreter.

pip install open_interpreter==0.2.0

**Comment by Badashphilosophy** [comment]
K coz i remembered it wasnt a numpy problem i kept trying and eventually solved it for me

I ran the commands

Apt list upgrade

Then 

Apt upgrade

Then 

Pip install open_interpreter==0.2.0

And it worked. Well it installed successfully. Interpreter is still having a problem starting but we are hopefully 1 step closer

Hope it works for you too bud

**Comment by nickfixit** [comment]
Same issue for me pixel 8 pro.

**Comment by okineadev** [comment]
Try this command:

```bash
pkg install libllvm
```
