### ISSUE TITLE
Cannot Initiate Open Interpreter on Termux

### ISSUE THREAD

**Issue by xhlsa** [MikeBirdTech/open-interpreter-termux#18]
~ $ interpreter
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/interpreter", line 5, in <module>                                                   from interpreter import interpreter
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/interpreter/__init__.py", line 1, in <module>
    from .core.core import OpenInterpreter
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/interpreter/core/core.py", line 14, in <module>
    from .computer.computer import Computer
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/interpreter/core/computer/computer.py", line 8, in <module>
    from .terminal.terminal import Terminal
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/interpreter/core/computer/terminal/terminal.py", line 6, in <module>
    from .languages.python import Python
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/interpreter/core/computer/terminal/languages/python.py", line 3, in <module>
    from .jupyter_language import JupyterLanguage
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/interpreter/core/computer/terminal/languages/jupyter_language.py", line 13, in <module>
    from jupyter_client import KernelManager
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_client/__init__.py", line 3, in <module>
    from .asynchronous import AsyncKernelClient
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/jupyter_client/asynchronous/client.py", line 8, in <module>
    import zmq.asyncio
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/__init__.py", line 52, in <module>
    from zmq import backend
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/__init__.py", line 30, in <module>
    raise original_error from None
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/__init__.py", line 25, in <module>
    _ns = select_backend(first)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/select.py", line 31, in select_backend         mod = import_module(name)
          ^^^^^^^^^^^^^^^^^^^                                   File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module                       return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import _zmq
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/cython/_zmq.cpython-311.so"...

**Comment by Sedrowow** [comment]
I have the same issue but with python 3.12
![Screenshot_20250128_085314_Termux.jpg](https://github.com/user-attachments/assets/453e67b9-08be-4c10-9819-ce30cf61e98d)

**Comment by no-tably** [comment]
I have the same issue!
![Screenshot_20250131-170547.png](https://github.com/user-attachments/assets/df896df7-0d40-40f2-a100-85dcd9db640c)
